export const PASSWORD_RESET_EXPIRATION_MINUTES =
  Number(process.env.PASSWORD_RESET_EXPIRATION_MINUTES) || 10;
export const PASSWORD_RESET_MAX_ATTEMPTS =
  Number(process.env.PASSWORD_RESET_MAX_ATTEMPTS) || 5;
export const PASSWORD_RESET_RESEND_COOLDOWN_SECONDS =
  Number(process.env.PASSWORD_RESET_RESEND_COOLDOWN_SECONDS) || 60;
export const PASSWORD_RESET_MAX_RESENDS =
  Number(process.env.PASSWORD_RESET_MAX_RESENDS) || 5;
export const PASSWORD_MIN_LENGTH = Number(process.env.PASSWORD_MIN_LENGTH) || 8;
